
services:
  # app:
  #   restart: always
  #   build: .
  #   container_name: "app"
  #   command: bash entrypoint.sh
  #   ports:
  #   - "8080:8080"
    # depends_on:
    #   - db_postgres

  # redis:
  #   restart: always
  #   image: redis
  #   container_name: "bot_redis_container"
  #   ports:
  #   - "6379:6379"

  db_postgres:
    image: postgres:15
    container_name: app_postgres_container
    restart: always
    env_file:
            - .env
    volumes:
      - app_postgres:/var/lib/postgresql/data
    ports:
    - 5432:5432


  pgadmin:
    image: dpage/pgadmin4
    container_name: app_pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    volumes:
      - app_pgadmin:/var/lib/pgadmin
    depends_on:
     - db_postgres

volumes:
 app_postgres:
 app_pgadmin:
